### ISSUE TITLE
customization

### ISSUE THREAD

**Issue by CSIAUD** [ThomasLatham/markdown-pdf-plus#5]
Hi,
Is there a way to customize margins, font, etc... ?

**Comment by ThomasLatham** [comment]
Hello! Thank you for your question, and sorry for the late response!

Yes, there is indeed a way to customize the styling (such as margins and fonts) of an exported PDF file. To help explain how this can be done with Markdown PDF Plus, let's reference [this project of mine](https://github.com/ThomasLatham/markdown-resume-template/tree/main/resume), a resume template that I wrote in Markdown, styled with CSS and exported to PDF:

1. Click on the link above to navigate to the `resume` directory in the `markdown-resume-template` repo.
![image](https://github.com/ThomasLatham/markdown-pdf-plus/assets/32628434/149491dd-de9d-4cf3-9cf4-3ef38fb0a356)

2. Click  on `resume.md`, and then on that page click on "Code".
![image](https://github.com/ThomasLatham/markdown-pdf-plus/assets/32628434/8860af03-4ef1-4775-a9d9-895f4ee7983c)

3. Notice the [`<link>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) HTML tag at the top of the Markdown document.
![image](https://github.com/ThomasLatham/markdown-pdf-plus/assets/32628434/04d1a6f7-c2c7-4da7-97ef-be1b607478b2)
Markdown allows developers to embed raw HTML directly into documents (as seen here), and this HTML element is what enables us to add styling via linking to a [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) styles heet. How are those styles defined precisely, we'll see in the next step, but for now do note the following:
  - The [`rel`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#rel) attribute has a value of `"stylesheet"`. This tells the underlying HTML of the Markdown file that the current `<link>` element is importing styles to the document.
  - The [`type`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#type) attribute has a value of `"text/css"`. This value is the mime type of a CSS style sheet, but CSS is the only style sheet used on the web, so the omission of this attribute (`type`) is actually recommended nowadays.
  - The [`href`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#href) attribute has a value of `"resume.css"`. This attribute tells the HTML where to find the style sheet via a URL. The URL in this example is relative to the Markdown file (the CSS file is in the same directory as the Markdown file, as we'll see), but the value of `href` can also be a URL to a CSS file file stored somewhere on the Web.

4. Navigate back to the location in step (1.), and click on `resume.css`. Notice that this is the file to which we pointed using the `href` attribute in the step (3.). Now let's analyze some details of this style sheet:
![image](https://github.com/ThomasLatham/markdown-pdf-plus/assets/32628434/5c3ef86a-c0d7-4dd0-ab4b-69911057162f)
  - The [`@page`](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) at-rule allows us to define particulars of exported PDF pages, such as the margin widths and the page size. Note that the extension setting `markdown-pdf-plus.usePageStyleFromCSS` *should* be set to `true` in order for this to work (although I think there may be a bug causing the `@page` rules to override default styles regardless of that setting).
  - The `body` CSS rules (applying to everything in the file `resume.md`, unless a rule with stronger specificity is applied somewhere) define a `font-size` of `12px` and a `font-family` (the font itself) of `Roboto`.

5. Now, when Markdown PDF Plus is used to export `resume.md` as a PDF, the result will be equivalent to the file `resume.pdf`, available in the location specified in step (1.).

Following these same steps for a different file, or even cloning `markdown-resume-template` and adjusting any of the templates to your own tastes, should produce PDFs from Markdown with the styles you're after, like fine-tuned margins and explicit fonts. Please let me know if I can be of further assistance, and if not feel free to close to the issue!

**Comment by CSIAUD** [comment]
Oh nice
Thanks
