### ISSUE TITLE
Page break

### ISSUE THREAD

**Issue by CSIAUD** [ThomasLatham/markdown-pdf-plus#6]
Hi, is there a way to force page break ( when exporting PDF ) ?

**Comment by fyrebase** [comment]
Just add `<div style="page-break-before:always"></div>` to force a page break in Markdown.

**Comment by ThomasLatham** [comment]
Hi @CSIAUD, thanks for your question! And thank you very much @fyrebase for answering it! 

I can confirm that, according to Kirk's instructions, adding a `<div>` styled as such in a Markdown file does indeed induce a page break in the resulting PDF when exporting via Markdown PDF Plus:
![image](https://github.com/ThomasLatham/markdown-pdf-plus/assets/32628434/ea2f7c3f-2017-4898-b45d-45db0f6cf093)

Cyprien, if you can confirm as well that this works for you, feel free to close this issue.
