### ISSUE TITLE
Customizable Margins

### ISSUE THREAD

**Issue by DragonCat4012** [ThomasLatham/markdown-pdf-plus#7]
I would really appreciate if the margins would be customizable bc 100px is  a really thic margin ^^" going into the files works but is not really efficient over multiple machines

**Comment by ThomasLatham** [comment]
Thanks for opening this issue! I'd be happy to implement a more convenient approach to customizing the margins. 

To confirm, [this answer](https://github.com/ThomasLatham/markdown-pdf-plus/issues/5#issuecomment-2180816708) does not suit your needs?

If not, then would extension-level settings to set the margins (e.g., `markdown-pdf-plus.margin-top`, `markdown-pdf-plus.margin-bottom`, etc.) be sufficient for your use case?

**Comment by ThomasLatham** [comment]
@DragonCat4012 if the `@page` at-rule method worked for you, would please close this issue as completed?
