### ISSUE TITLE
Feature: Render Mermaid Diagrams

### ISSUE THREAD

**Issue by DragonCat4012** [ThomasLatham/markdown-pdf-plus#8]
Rendering mermaid diagrams would be really cool :3

**Comment by ThomasLatham** [comment]
Thanks for introducing me to [Mermaid](https://mermaid.js.org/) (this is what you're talking about right?). After a quick look into the  usage docs, it _seems_ like rendering Mermaid diagrams would be pretty feasible for Markdown PDF Plus. I'll give it a shot!

**Comment by DragonCat4012** [comment]
yes! github does render them in their markdown files and its pretty neat to include them in documents :3

**Comment by ThomasLatham** [comment]
Version 1.2.0 just deployed with (hopefully working) Mermaid support!

**Comment by ThomasLatham** [comment]
@DragonCat4012 if you can confirm that version 1.2.0 enables you to render Mermaid diagrams, could you please close this issue as completed?

**Comment by DragonCat4012** [comment]
> Version 1.2.0 just deployed with (hopefully working) Mermaid support!

thx works as i would expect it nice :0
