### ISSUE TITLE
Background Image support in PDF

### ISSUE THREAD

**Issue by czarodziej91** [ThomasLatham/markdown-pdf-plus#9]
It seems, that currently background-images are not supported on PDF export.

Reproduction steps:
1. In your md file add a reference to stylesheet. `<link rel="stylesheet" type="text/css" href="../Styles/main.css">`.
2. In your stylesheet set a background image property with an url `body > div { background-image: url("./Images/tausta.png");}`.
3. Export your md file to HTML. - Background image will load as expected.
4. Export your md file to PDF. - Background Image will not be loaded in PDF.

I can print the PDF from the HTML exported version of my md file. In Chrome browser I can go to Options -> Print and mark "Print Background Colors and Images" option to true
![image](https://github.com/user-attachments/assets/8db8f045-0140-4ed7-9c83-bc001ad0200b)

I suppose markdown-pdf-plus does not support that option when exporting to PDF. It would be nice if it could be set in an extension settings or was always set by default.

Btw since I have the opportunity - very nice solution you created, thank you very much :)

**Comment by ThomasLatham** [comment]
Thank you very much for opening this issue and for the detailed reproduction steps! I have just now used those steps to confirm your findings, and I will start on implementing support for background images.

Thank you so much too for using and appreciating this extension!

**Comment by ThomasLatham** [comment]
Hi @czarodziej91, I've just release v1.2.1 which includes changes to address this issue. Can you please confirm whether this new version provides support for background images when exporting PDFs?

**Comment by czarodziej91** [comment]
Hi Thomas, once I updated a plugin, I started to receive a following error:
![image](https://github.com/user-attachments/assets/8a778d32-f027-4ad0-8a3c-272891bde1c0)
So I cannot quite check the functionality behind. Once I downgraded to version 1.2.0 of the extension everything works the old way, so there is no error.

**Comment by ThomasLatham** [comment]
Hmm, it seems I've broken the extension. Thanks for the update. I'll get to work on fixing it as soon as I can

**Comment by czarodziej91** [comment]
Sure, I'll keep following the issue. For me, the background part is not urgent at all, as a workaround exists with printing from HTML exported file.

**Comment by ThomasLatham** [comment]
Thanks for your patience. I just released v1.2.3 which *should* not be broken and also should support background images.

**Comment by czarodziej91** [comment]
Awesome, works perfectly in all cases so far. Thank you :)
